# Application context-Path:
server:
  port: 9090

ame:
  context-path: /weather
  email:
    host: host
    username: username
    password: password
    sender: sender@sender.com
    port: 587

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_ame_weather?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ame_weather
    password: ame_weather
    hikari:
      maximumPoolSize: 4
  flyway:
    url: jdbc:mysql://localhost:3306/db_ame_weather?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ame_weather
    password: ame_weather
    validate-on-migrate: false
  cache:
    clearAllCachesCron: '0 0 */1 ? * *'

# Webflux retry configuration
retryable:
  max-retries: 5
  min-duration: 5
  max-duration: 20

#logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.com.amedigital: DEBUG
    reactor.netty.http.client: INFO
  pattern:
    console: '%highlight(<<%-5level>>) %d{HH:mm:ss:SSS} [%thread]%X{user} %magenta(%c{0}.%M) - %m%n'

  # Actuator configs
management:
  endpoints.web.base-path: /
  endpoint.flyway.enabled: true

partner:
  url: http://servicos.cptec.inpe.br/XML